# Generated by Django 4.2.9 on 2026-05-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_form', '0002_itemcard_delete_opportunitymaster_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feasibility',
            table='tbl_feasibility',
        ),
    ]
