# Generated by Django 4.2.9 on 2026-05-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_creation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uom_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fixture_no', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_meft', models.CharField(blank=True, max_length=50, null=True)),
                ('action_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_ecn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_parts', models.CharField(blank=True, max_length=50, null=True)),
                ('last_date_modified', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_creation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('table_id', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_bom_header',
            },
        ),
        migrations.CreateModel(
            name='BOMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uom_code', models.CharField(blank=True, max_length=50, null=True)),
                ('categorisation', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_link_code', models.CharField(blank=True, max_length=100, null=True)),
                ('part_status', models.CharField(blank=True, max_length=50, null=True)),
                ('grp_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('grp_part_descp', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='BOM.bomheader')),
            ],
            options={
                'db_table': 'tbl_bom_transaction',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
