# Generated by Django 4.2.9 on 2026-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostingBCCal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomCreation',
            fields=[
                ('bomcreation_id', models.IntegerField(db_column='BOMCreation_ID', primary_key=True, serialize=False)),
                ('table_id', models.IntegerField(blank=True, db_column='table_id', null=True)),
                ('customer_id', models.CharField(blank=True, db_column='Customer_ID', max_length=50, null=True)),
                ('item_creation_id', models.CharField(blank=True, db_column='ItemCreation_Id', max_length=50, null=True)),
                ('remark', models.TextField(blank=True, db_column='Remark', null=True)),
            ],
            options={
                'db_table': 'tbl_BomCreation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BopCreation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, db_column='customer_id', max_length=50, null=True)),
                ('itemcreation_id', models.CharField(blank=True, db_column='itemcreation_id', max_length=50, null=True)),
                ('action_status', models.CharField(blank=True, db_column='action_status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_bopcreation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostingInternalConversion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('mhr', models.DecimalField(blank=True, db_column='mhr', decimal_places=4, max_digits=12, null=True)),
                ('run_time_sec', models.DecimalField(blank=True, db_column='run_time_sec', decimal_places=4, max_digits=12, null=True)),
                ('perhouroutput', models.DecimalField(blank=True, db_column='perhouroutput', decimal_places=4, max_digits=12, null=True)),
                ('rateperunit', models.DecimalField(blank=True, db_column='rateperunit', decimal_places=4, max_digits=12, null=True)),
                ('boq', models.DecimalField(blank=True, db_column='boq', decimal_places=4, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, db_column='total', decimal_places=4, max_digits=15, null=True)),
                ('contributionpercentage', models.DecimalField(blank=True, db_column='contributionpercentage', decimal_places=4, max_digits=8, null=True)),
                ('mhr_category', models.CharField(blank=True, db_column='mhr_category', max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, db_column='customer_id', max_length=50, null=True)),
                ('itemcreation_id', models.CharField(blank=True, db_column='itemcreation_id', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_costing_internalconversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DTAssignmentYearData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('item_creation', models.CharField(blank=True, db_column='itemcreation_id', db_index=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, db_column='customer_id', max_length=50, null=True)),
                ('category', models.CharField(blank=True, db_column='category', max_length=100, null=True)),
                ('assignment_year', models.IntegerField(blank=True, db_column='year', null=True)),
                ('assigned_value', models.DecimalField(blank=True, db_column='cost', decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_dtassigmentyeardata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DTCategoryList',
            fields=[
                ('category_name', models.CharField(db_column='category', db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, db_column='currency', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_dtcategorylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormsDetails',
            fields=[
                ('Sr_No', models.AutoField(db_column='sr_no', primary_key=True, serialize=False)),
                ('Norms_Code', models.CharField(blank=True, db_column='norms_code', max_length=255, null=True)),
                ('Sheet_Name', models.CharField(blank=True, db_column='sheet_name', max_length=255, null=True)),
                ('Customer_Name', models.CharField(blank=True, db_column='customer_name', max_length=255, null=True)),
                ('Cell_Location', models.CharField(blank=True, db_column='cell_location', max_length=500, null=True)),
                ('Cell_Value', models.TextField(blank=True, db_column='cell_value', null=True)),
                ('Location', models.CharField(blank=True, db_column='location', max_length=500, null=True)),
                ('Export_Path', models.TextField(blank=True, db_column='export_path', null=True)),
                ('local_bo_flag', models.BooleanField(blank=True, db_column='local_bo_flag', default=False, null=True)),
                ('total_local_bo_flag', models.BooleanField(blank=True, db_column='total_local_bo_flag', default=False, null=True)),
                ('packaging_series', models.BooleanField(blank=True, db_column='packaging_series', default=False, null=True)),
                ('packaging_proto', models.BooleanField(blank=True, db_column='packaging_proto', default=False, null=True)),
                ('os_template', models.CharField(blank=True, db_column='os_template', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_normsdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferSheetPartDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(blank=True, db_column='Part_Number', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('unit_of_measure_code', models.CharField(blank=True, db_column='Unit_of_Measure_Code', max_length=20, null=True)),
                ('quantity', models.FloatField(db_column='Quantity', default=0.0)),
                ('internal_cost', models.FloatField(db_column='Internal_Cost', default=0.0)),
                ('settle_price', models.FloatField(blank=True, db_column='Settle Price', null=True)),
                ('categorisation', models.CharField(blank=True, db_column='Categorisation', max_length=50, null=True)),
                ('customer_id', models.IntegerField(db_column='Customer_ID')),
                ('itemcreation_id', models.IntegerField(db_column='ItemCreation_Id')),
                ('bomcreation_id', models.IntegerField(blank=True, db_column='BOMCreation_ID', null=True)),
                ('table_id', models.IntegerField(blank=True, db_column='Table_id', null=True)),
            ],
            options={
                'db_table': 'tbl_OfferSheetPartDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferSheetRMConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_material_desc', models.TextField(blank=True, db_column='raw_material_description', null=True)),
                ('tube_size', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('internal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, db_column='rateperunit', decimal_places=2, max_digits=12, null=True)),
                ('qnty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rm_flag', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('item_creation_id', models.CharField(blank=True, db_column='itemcreation_id', max_length=50, null=True)),
                ('process_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_offersheetrmconversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RFQDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('itemcreation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_rfq_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferSheetBOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, db_column='part_number', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('unit_of_measure_code', models.CharField(blank=True, db_column='unit_of_measure_code', max_length=20, null=True)),
                ('quantity', models.FloatField(db_column='quantity', default=0.0)),
                ('internal_cost', models.FloatField(db_column='internal_cost', default=0.0)),
                ('settle_price', models.FloatField(db_column='settle_price', default=0.0)),
                ('cost', models.FloatField(db_column='cost', default=0.0)),
                ('categorisation', models.CharField(blank=True, db_column='categorisation', max_length=50, null=True)),
                ('customer_id', models.CharField(db_column='customer_id', max_length=50)),
                ('itemcreation_id', models.BigIntegerField(db_column='itemcreation_id')),
                ('boc_type', models.CharField(db_column='boc_type', default='Local', max_length=50)),
                ('update_by', models.CharField(db_column='update_by', default='USER', max_length=100)),
            ],
            options={
                'db_table': 'ztbl_offersheet_boc',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
